// AUTO-GENERATED — do not edit by hand.
// Regenerate with `npm run generate` after refreshing data via `npm run fetch-data`.
// Source: list-one.xml (SIX Group)

import type { Currency } from "./types.js";

/**
 * ISO 4217 publication date of the data embedded in this module.
 */
export const PUBLISHED_AT = "2026-01-01" as const;

/**
 * Frozen array of every active ISO 4217 currency, sorted by alphabetic code.
 */
export const CURRENCIES: readonly Currency[] = Object.freeze([
	Object.freeze({
		alphabeticCode: "AED",
		numericCode: "784",
		minorUnits: 2,
		name: "UAE Dirham",
		countryCodes: ["AE"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "AFN",
		numericCode: "971",
		minorUnits: 2,
		name: "Afghani",
		countryCodes: ["AF"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "ALL",
		numericCode: "008",
		minorUnits: 2,
		name: "Lek",
		countryCodes: ["AL"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "AMD",
		numericCode: "051",
		minorUnits: 2,
		name: "Armenian Dram",
		countryCodes: ["AM"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "AOA",
		numericCode: "973",
		minorUnits: 2,
		name: "Kwanza",
		countryCodes: ["AO"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "ARS",
		numericCode: "032",
		minorUnits: 2,
		name: "Argentine Peso",
		countryCodes: ["AR"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "AUD",
		numericCode: "036",
		minorUnits: 2,
		name: "Australian Dollar",
		countryCodes: ["AU", "CC", "CX", "HM", "KI", "NF", "NR", "TV"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "AWG",
		numericCode: "533",
		minorUnits: 2,
		name: "Aruban Florin",
		countryCodes: ["AW"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "AZN",
		numericCode: "944",
		minorUnits: 2,
		name: "Azerbaijan Manat",
		countryCodes: ["AZ"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "BAM",
		numericCode: "977",
		minorUnits: 2,
		name: "Convertible Mark",
		countryCodes: ["BA"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "BBD",
		numericCode: "052",
		minorUnits: 2,
		name: "Barbados Dollar",
		countryCodes: ["BB"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "BDT",
		numericCode: "050",
		minorUnits: 2,
		name: "Taka",
		countryCodes: ["BD"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "BHD",
		numericCode: "048",
		minorUnits: 3,
		name: "Bahraini Dinar",
		countryCodes: ["BH"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "BIF",
		numericCode: "108",
		minorUnits: 0,
		name: "Burundi Franc",
		countryCodes: ["BI"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "BMD",
		numericCode: "060",
		minorUnits: 2,
		name: "Bermudian Dollar",
		countryCodes: ["BM"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "BND",
		numericCode: "096",
		minorUnits: 2,
		name: "Brunei Dollar",
		countryCodes: ["BN"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "BOB",
		numericCode: "068",
		minorUnits: 2,
		name: "Boliviano",
		countryCodes: ["BO"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "BOV",
		numericCode: "984",
		minorUnits: 2,
		name: "Mvdol",
		countryCodes: ["BO"],
		isFund: true,
		kind: "fund",
	}),
	Object.freeze({
		alphabeticCode: "BRL",
		numericCode: "986",
		minorUnits: 2,
		name: "Brazilian Real",
		countryCodes: ["BR"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "BSD",
		numericCode: "044",
		minorUnits: 2,
		name: "Bahamian Dollar",
		countryCodes: ["BS"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "BTN",
		numericCode: "064",
		minorUnits: 2,
		name: "Ngultrum",
		countryCodes: ["BT"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "BWP",
		numericCode: "072",
		minorUnits: 2,
		name: "Pula",
		countryCodes: ["BW"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "BYN",
		numericCode: "933",
		minorUnits: 2,
		name: "Belarusian Ruble",
		countryCodes: ["BY"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "BZD",
		numericCode: "084",
		minorUnits: 2,
		name: "Belize Dollar",
		countryCodes: ["BZ"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "CAD",
		numericCode: "124",
		minorUnits: 2,
		name: "Canadian Dollar",
		countryCodes: ["CA"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "CDF",
		numericCode: "976",
		minorUnits: 2,
		name: "Congolese Franc",
		countryCodes: ["CD"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "CHE",
		numericCode: "947",
		minorUnits: 2,
		name: "WIR Euro",
		countryCodes: ["CH"],
		isFund: true,
		kind: "fund",
	}),
	Object.freeze({
		alphabeticCode: "CHF",
		numericCode: "756",
		minorUnits: 2,
		name: "Swiss Franc",
		countryCodes: ["CH", "LI"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "CHW",
		numericCode: "948",
		minorUnits: 2,
		name: "WIR Franc",
		countryCodes: ["CH"],
		isFund: true,
		kind: "fund",
	}),
	Object.freeze({
		alphabeticCode: "CLF",
		numericCode: "990",
		minorUnits: 4,
		name: "Unidad de Fomento",
		countryCodes: ["CL"],
		isFund: true,
		kind: "fund",
	}),
	Object.freeze({
		alphabeticCode: "CLP",
		numericCode: "152",
		minorUnits: 0,
		name: "Chilean Peso",
		countryCodes: ["CL"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "CNY",
		numericCode: "156",
		minorUnits: 2,
		name: "Yuan Renminbi",
		countryCodes: ["CN"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "COP",
		numericCode: "170",
		minorUnits: 2,
		name: "Colombian Peso",
		countryCodes: ["CO"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "COU",
		numericCode: "970",
		minorUnits: 2,
		name: "Unidad de Valor Real",
		countryCodes: ["CO"],
		isFund: true,
		kind: "fund",
	}),
	Object.freeze({
		alphabeticCode: "CRC",
		numericCode: "188",
		minorUnits: 2,
		name: "Costa Rican Colon",
		countryCodes: ["CR"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "CUP",
		numericCode: "192",
		minorUnits: 2,
		name: "Cuban Peso",
		countryCodes: ["CU"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "CVE",
		numericCode: "132",
		minorUnits: 2,
		name: "Cabo Verde Escudo",
		countryCodes: ["CV"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "CZK",
		numericCode: "203",
		minorUnits: 2,
		name: "Czech Koruna",
		countryCodes: ["CZ"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "DJF",
		numericCode: "262",
		minorUnits: 0,
		name: "Djibouti Franc",
		countryCodes: ["DJ"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "DKK",
		numericCode: "208",
		minorUnits: 2,
		name: "Danish Krone",
		countryCodes: ["DK", "FO", "GL"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "DOP",
		numericCode: "214",
		minorUnits: 2,
		name: "Dominican Peso",
		countryCodes: ["DO"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "DZD",
		numericCode: "012",
		minorUnits: 2,
		name: "Algerian Dinar",
		countryCodes: ["DZ"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "EGP",
		numericCode: "818",
		minorUnits: 2,
		name: "Egyptian Pound",
		countryCodes: ["EG"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "ERN",
		numericCode: "232",
		minorUnits: 2,
		name: "Nakfa",
		countryCodes: ["ER"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "ETB",
		numericCode: "230",
		minorUnits: 2,
		name: "Ethiopian Birr",
		countryCodes: ["ET"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "EUR",
		numericCode: "978",
		minorUnits: 2,
		name: "Euro",
		countryCodes: [
			"AD",
			"AT",
			"AX",
			"BE",
			"BG",
			"BL",
			"CY",
			"DE",
			"EE",
			"ES",
			"EU",
			"FI",
			"FR",
			"GF",
			"GP",
			"GR",
			"HR",
			"IE",
			"IT",
			"LT",
			"LU",
			"LV",
			"MC",
			"ME",
			"MF",
			"MQ",
			"MT",
			"NL",
			"PM",
			"PT",
			"RE",
			"SI",
			"SK",
			"SM",
			"TF",
			"VA",
			"YT",
		],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "FJD",
		numericCode: "242",
		minorUnits: 2,
		name: "Fiji Dollar",
		countryCodes: ["FJ"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "FKP",
		numericCode: "238",
		minorUnits: 2,
		name: "Falkland Islands Pound",
		countryCodes: ["FK"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "GBP",
		numericCode: "826",
		minorUnits: 2,
		name: "Pound Sterling",
		countryCodes: ["GB", "GG", "IM", "JE"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "GEL",
		numericCode: "981",
		minorUnits: 2,
		name: "Lari",
		countryCodes: ["GE"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "GHS",
		numericCode: "936",
		minorUnits: 2,
		name: "Ghana Cedi",
		countryCodes: ["GH"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "GIP",
		numericCode: "292",
		minorUnits: 2,
		name: "Gibraltar Pound",
		countryCodes: ["GI"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "GMD",
		numericCode: "270",
		minorUnits: 2,
		name: "Dalasi",
		countryCodes: ["GM"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "GNF",
		numericCode: "324",
		minorUnits: 0,
		name: "Guinean Franc",
		countryCodes: ["GN"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "GTQ",
		numericCode: "320",
		minorUnits: 2,
		name: "Quetzal",
		countryCodes: ["GT"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "GYD",
		numericCode: "328",
		minorUnits: 2,
		name: "Guyana Dollar",
		countryCodes: ["GY"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "HKD",
		numericCode: "344",
		minorUnits: 2,
		name: "Hong Kong Dollar",
		countryCodes: ["HK"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "HNL",
		numericCode: "340",
		minorUnits: 2,
		name: "Lempira",
		countryCodes: ["HN"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "HTG",
		numericCode: "332",
		minorUnits: 2,
		name: "Gourde",
		countryCodes: ["HT"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "HUF",
		numericCode: "348",
		minorUnits: 2,
		name: "Forint",
		countryCodes: ["HU"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "IDR",
		numericCode: "360",
		minorUnits: 2,
		name: "Rupiah",
		countryCodes: ["ID"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "ILS",
		numericCode: "376",
		minorUnits: 2,
		name: "New Israeli Sheqel",
		countryCodes: ["IL"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "INR",
		numericCode: "356",
		minorUnits: 2,
		name: "Indian Rupee",
		countryCodes: ["BT", "IN"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "IQD",
		numericCode: "368",
		minorUnits: 3,
		name: "Iraqi Dinar",
		countryCodes: ["IQ"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "IRR",
		numericCode: "364",
		minorUnits: 2,
		name: "Iranian Rial",
		countryCodes: ["IR"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "ISK",
		numericCode: "352",
		minorUnits: 0,
		name: "Iceland Krona",
		countryCodes: ["IS"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "JMD",
		numericCode: "388",
		minorUnits: 2,
		name: "Jamaican Dollar",
		countryCodes: ["JM"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "JOD",
		numericCode: "400",
		minorUnits: 3,
		name: "Jordanian Dinar",
		countryCodes: ["JO"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "JPY",
		numericCode: "392",
		minorUnits: 0,
		name: "Yen",
		countryCodes: ["JP"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "KES",
		numericCode: "404",
		minorUnits: 2,
		name: "Kenyan Shilling",
		countryCodes: ["KE"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "KGS",
		numericCode: "417",
		minorUnits: 2,
		name: "Som",
		countryCodes: ["KG"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "KHR",
		numericCode: "116",
		minorUnits: 2,
		name: "Riel",
		countryCodes: ["KH"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "KMF",
		numericCode: "174",
		minorUnits: 0,
		name: "Comorian Franc",
		countryCodes: ["KM"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "KPW",
		numericCode: "408",
		minorUnits: 2,
		name: "North Korean Won",
		countryCodes: ["KP"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "KRW",
		numericCode: "410",
		minorUnits: 0,
		name: "Won",
		countryCodes: ["KR"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "KWD",
		numericCode: "414",
		minorUnits: 3,
		name: "Kuwaiti Dinar",
		countryCodes: ["KW"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "KYD",
		numericCode: "136",
		minorUnits: 2,
		name: "Cayman Islands Dollar",
		countryCodes: ["KY"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "KZT",
		numericCode: "398",
		minorUnits: 2,
		name: "Tenge",
		countryCodes: ["KZ"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "LAK",
		numericCode: "418",
		minorUnits: 2,
		name: "Lao Kip",
		countryCodes: ["LA"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "LBP",
		numericCode: "422",
		minorUnits: 2,
		name: "Lebanese Pound",
		countryCodes: ["LB"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "LKR",
		numericCode: "144",
		minorUnits: 2,
		name: "Sri Lanka Rupee",
		countryCodes: ["LK"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "LRD",
		numericCode: "430",
		minorUnits: 2,
		name: "Liberian Dollar",
		countryCodes: ["LR"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "LSL",
		numericCode: "426",
		minorUnits: 2,
		name: "Loti",
		countryCodes: ["LS"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "LYD",
		numericCode: "434",
		minorUnits: 3,
		name: "Libyan Dinar",
		countryCodes: ["LY"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "MAD",
		numericCode: "504",
		minorUnits: 2,
		name: "Moroccan Dirham",
		countryCodes: ["EH", "MA"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "MDL",
		numericCode: "498",
		minorUnits: 2,
		name: "Moldovan Leu",
		countryCodes: ["MD"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "MGA",
		numericCode: "969",
		minorUnits: 2,
		name: "Malagasy Ariary",
		countryCodes: ["MG"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "MKD",
		numericCode: "807",
		minorUnits: 2,
		name: "Denar",
		countryCodes: ["MK"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "MMK",
		numericCode: "104",
		minorUnits: 2,
		name: "Kyat",
		countryCodes: ["MM"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "MNT",
		numericCode: "496",
		minorUnits: 2,
		name: "Tugrik",
		countryCodes: ["MN"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "MOP",
		numericCode: "446",
		minorUnits: 2,
		name: "Pataca",
		countryCodes: ["MO"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "MRU",
		numericCode: "929",
		minorUnits: 2,
		name: "Ouguiya",
		countryCodes: ["MR"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "MUR",
		numericCode: "480",
		minorUnits: 2,
		name: "Mauritius Rupee",
		countryCodes: ["MU"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "MVR",
		numericCode: "462",
		minorUnits: 2,
		name: "Rufiyaa",
		countryCodes: ["MV"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "MWK",
		numericCode: "454",
		minorUnits: 2,
		name: "Malawi Kwacha",
		countryCodes: ["MW"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "MXN",
		numericCode: "484",
		minorUnits: 2,
		name: "Mexican Peso",
		countryCodes: ["MX"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "MXV",
		numericCode: "979",
		minorUnits: 2,
		name: "Mexican Unidad de Inversion (UDI)",
		countryCodes: ["MX"],
		isFund: true,
		kind: "fund",
	}),
	Object.freeze({
		alphabeticCode: "MYR",
		numericCode: "458",
		minorUnits: 2,
		name: "Malaysian Ringgit",
		countryCodes: ["MY"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "MZN",
		numericCode: "943",
		minorUnits: 2,
		name: "Mozambique Metical",
		countryCodes: ["MZ"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "NAD",
		numericCode: "516",
		minorUnits: 2,
		name: "Namibia Dollar",
		countryCodes: ["NA"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "NGN",
		numericCode: "566",
		minorUnits: 2,
		name: "Naira",
		countryCodes: ["NG"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "NIO",
		numericCode: "558",
		minorUnits: 2,
		name: "Cordoba Oro",
		countryCodes: ["NI"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "NOK",
		numericCode: "578",
		minorUnits: 2,
		name: "Norwegian Krone",
		countryCodes: ["BV", "NO", "SJ"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "NPR",
		numericCode: "524",
		minorUnits: 2,
		name: "Nepalese Rupee",
		countryCodes: ["NP"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "NZD",
		numericCode: "554",
		minorUnits: 2,
		name: "New Zealand Dollar",
		countryCodes: ["CK", "NU", "NZ", "PN", "TK"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "OMR",
		numericCode: "512",
		minorUnits: 3,
		name: "Rial Omani",
		countryCodes: ["OM"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "PAB",
		numericCode: "590",
		minorUnits: 2,
		name: "Balboa",
		countryCodes: ["PA"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "PEN",
		numericCode: "604",
		minorUnits: 2,
		name: "Sol",
		countryCodes: ["PE"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "PGK",
		numericCode: "598",
		minorUnits: 2,
		name: "Kina",
		countryCodes: ["PG"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "PHP",
		numericCode: "608",
		minorUnits: 2,
		name: "Philippine Peso",
		countryCodes: ["PH"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "PKR",
		numericCode: "586",
		minorUnits: 2,
		name: "Pakistan Rupee",
		countryCodes: ["PK"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "PLN",
		numericCode: "985",
		minorUnits: 2,
		name: "Zloty",
		countryCodes: ["PL"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "PYG",
		numericCode: "600",
		minorUnits: 0,
		name: "Guarani",
		countryCodes: ["PY"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "QAR",
		numericCode: "634",
		minorUnits: 2,
		name: "Qatari Rial",
		countryCodes: ["QA"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "RON",
		numericCode: "946",
		minorUnits: 2,
		name: "Romanian Leu",
		countryCodes: ["RO"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "RSD",
		numericCode: "941",
		minorUnits: 2,
		name: "Serbian Dinar",
		countryCodes: ["RS"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "RUB",
		numericCode: "643",
		minorUnits: 2,
		name: "Russian Ruble",
		countryCodes: ["RU"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "RWF",
		numericCode: "646",
		minorUnits: 0,
		name: "Rwanda Franc",
		countryCodes: ["RW"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "SAR",
		numericCode: "682",
		minorUnits: 2,
		name: "Saudi Riyal",
		countryCodes: ["SA"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "SBD",
		numericCode: "090",
		minorUnits: 2,
		name: "Solomon Islands Dollar",
		countryCodes: ["SB"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "SCR",
		numericCode: "690",
		minorUnits: 2,
		name: "Seychelles Rupee",
		countryCodes: ["SC"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "SDG",
		numericCode: "938",
		minorUnits: 2,
		name: "Sudanese Pound",
		countryCodes: ["SD"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "SEK",
		numericCode: "752",
		minorUnits: 2,
		name: "Swedish Krona",
		countryCodes: ["SE"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "SGD",
		numericCode: "702",
		minorUnits: 2,
		name: "Singapore Dollar",
		countryCodes: ["SG"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "SHP",
		numericCode: "654",
		minorUnits: 2,
		name: "Saint Helena Pound",
		countryCodes: ["SH"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "SLE",
		numericCode: "925",
		minorUnits: 2,
		name: "Leone",
		countryCodes: ["SL"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "SOS",
		numericCode: "706",
		minorUnits: 2,
		name: "Somali Shilling",
		countryCodes: ["SO"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "SRD",
		numericCode: "968",
		minorUnits: 2,
		name: "Surinam Dollar",
		countryCodes: ["SR"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "SSP",
		numericCode: "728",
		minorUnits: 2,
		name: "South Sudanese Pound",
		countryCodes: ["SS"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "STN",
		numericCode: "930",
		minorUnits: 2,
		name: "Dobra",
		countryCodes: ["ST"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "SVC",
		numericCode: "222",
		minorUnits: 2,
		name: "El Salvador Colon",
		countryCodes: ["SV"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "SYP",
		numericCode: "760",
		minorUnits: 2,
		name: "Syrian Pound",
		countryCodes: ["SY"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "SZL",
		numericCode: "748",
		minorUnits: 2,
		name: "Lilangeni",
		countryCodes: ["SZ"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "THB",
		numericCode: "764",
		minorUnits: 2,
		name: "Baht",
		countryCodes: ["TH"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "TJS",
		numericCode: "972",
		minorUnits: 2,
		name: "Somoni",
		countryCodes: ["TJ"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "TMT",
		numericCode: "934",
		minorUnits: 2,
		name: "Turkmenistan New Manat",
		countryCodes: ["TM"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "TND",
		numericCode: "788",
		minorUnits: 3,
		name: "Tunisian Dinar",
		countryCodes: ["TN"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "TOP",
		numericCode: "776",
		minorUnits: 2,
		name: "Pa’anga",
		countryCodes: ["TO"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "TRY",
		numericCode: "949",
		minorUnits: 2,
		name: "Turkish Lira",
		countryCodes: ["TR"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "TTD",
		numericCode: "780",
		minorUnits: 2,
		name: "Trinidad and Tobago Dollar",
		countryCodes: ["TT"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "TWD",
		numericCode: "901",
		minorUnits: 2,
		name: "New Taiwan Dollar",
		countryCodes: ["TW"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "TZS",
		numericCode: "834",
		minorUnits: 2,
		name: "Tanzanian Shilling",
		countryCodes: ["TZ"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "UAH",
		numericCode: "980",
		minorUnits: 2,
		name: "Hryvnia",
		countryCodes: ["UA"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "UGX",
		numericCode: "800",
		minorUnits: 0,
		name: "Uganda Shilling",
		countryCodes: ["UG"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "USD",
		numericCode: "840",
		minorUnits: 2,
		name: "US Dollar",
		countryCodes: [
			"AS",
			"BQ",
			"EC",
			"FM",
			"GU",
			"HT",
			"IO",
			"MH",
			"MP",
			"PA",
			"PR",
			"PW",
			"SV",
			"TC",
			"TL",
			"UM",
			"US",
			"VG",
			"VI",
		],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "USN",
		numericCode: "997",
		minorUnits: 2,
		name: "US Dollar (Next day)",
		countryCodes: ["US"],
		isFund: true,
		kind: "fund",
	}),
	Object.freeze({
		alphabeticCode: "UYI",
		numericCode: "940",
		minorUnits: 0,
		name: "Uruguay Peso en Unidades Indexadas (UI)",
		countryCodes: ["UY"],
		isFund: true,
		kind: "fund",
	}),
	Object.freeze({
		alphabeticCode: "UYU",
		numericCode: "858",
		minorUnits: 2,
		name: "Peso Uruguayo",
		countryCodes: ["UY"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "UYW",
		numericCode: "927",
		minorUnits: 4,
		name: "Unidad Previsional",
		countryCodes: ["UY"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "UZS",
		numericCode: "860",
		minorUnits: 2,
		name: "Uzbekistan Sum",
		countryCodes: ["UZ"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "VED",
		numericCode: "926",
		minorUnits: 2,
		name: "Bolívar Soberano",
		countryCodes: ["VE"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "VES",
		numericCode: "928",
		minorUnits: 2,
		name: "Bolívar Soberano",
		countryCodes: ["VE"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "VND",
		numericCode: "704",
		minorUnits: 0,
		name: "Dong",
		countryCodes: ["VN"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "VUV",
		numericCode: "548",
		minorUnits: 0,
		name: "Vatu",
		countryCodes: ["VU"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "WST",
		numericCode: "882",
		minorUnits: 2,
		name: "Tala",
		countryCodes: ["WS"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "XAD",
		numericCode: "396",
		minorUnits: 2,
		name: "Arab Accounting Dinar",
		countryCodes: [],
		isFund: false,
		kind: "special",
	}),
	Object.freeze({
		alphabeticCode: "XAF",
		numericCode: "950",
		minorUnits: 0,
		name: "CFA Franc BEAC",
		countryCodes: ["CF", "CG", "CM", "GA", "GQ", "TD"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "XAG",
		numericCode: "961",
		minorUnits: null,
		name: "Silver",
		countryCodes: [],
		isFund: false,
		kind: "metal",
	}),
	Object.freeze({
		alphabeticCode: "XAU",
		numericCode: "959",
		minorUnits: null,
		name: "Gold",
		countryCodes: [],
		isFund: false,
		kind: "metal",
	}),
	Object.freeze({
		alphabeticCode: "XBA",
		numericCode: "955",
		minorUnits: null,
		name: "Bond Markets Unit European Composite Unit (EURCO)",
		countryCodes: [],
		isFund: false,
		kind: "special",
	}),
	Object.freeze({
		alphabeticCode: "XBB",
		numericCode: "956",
		minorUnits: null,
		name: "Bond Markets Unit European Monetary Unit (E.M.U.-6)",
		countryCodes: [],
		isFund: false,
		kind: "special",
	}),
	Object.freeze({
		alphabeticCode: "XBC",
		numericCode: "957",
		minorUnits: null,
		name: "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)",
		countryCodes: [],
		isFund: false,
		kind: "special",
	}),
	Object.freeze({
		alphabeticCode: "XBD",
		numericCode: "958",
		minorUnits: null,
		name: "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)",
		countryCodes: [],
		isFund: false,
		kind: "special",
	}),
	Object.freeze({
		alphabeticCode: "XCD",
		numericCode: "951",
		minorUnits: 2,
		name: "East Caribbean Dollar",
		countryCodes: ["AG", "AI", "DM", "GD", "KN", "LC", "MS", "VC"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "XCG",
		numericCode: "532",
		minorUnits: 2,
		name: "Caribbean Guilder",
		countryCodes: ["CW", "SX"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "XDR",
		numericCode: "960",
		minorUnits: null,
		name: "SDR (Special Drawing Right)",
		countryCodes: [],
		isFund: false,
		kind: "special",
	}),
	Object.freeze({
		alphabeticCode: "XOF",
		numericCode: "952",
		minorUnits: 0,
		name: "CFA Franc BCEAO",
		countryCodes: ["BF", "BJ", "CI", "GW", "ML", "NE", "SN", "TG"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "XPD",
		numericCode: "964",
		minorUnits: null,
		name: "Palladium",
		countryCodes: [],
		isFund: false,
		kind: "metal",
	}),
	Object.freeze({
		alphabeticCode: "XPF",
		numericCode: "953",
		minorUnits: 0,
		name: "CFP Franc",
		countryCodes: ["NC", "PF", "WF"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "XPT",
		numericCode: "962",
		minorUnits: null,
		name: "Platinum",
		countryCodes: [],
		isFund: false,
		kind: "metal",
	}),
	Object.freeze({
		alphabeticCode: "XSU",
		numericCode: "994",
		minorUnits: null,
		name: "Sucre",
		countryCodes: [],
		isFund: false,
		kind: "special",
	}),
	Object.freeze({
		alphabeticCode: "XTS",
		numericCode: "963",
		minorUnits: null,
		name: "Codes specifically reserved for testing purposes",
		countryCodes: [],
		isFund: false,
		kind: "special",
	}),
	Object.freeze({
		alphabeticCode: "XUA",
		numericCode: "965",
		minorUnits: null,
		name: "ADB Unit of Account",
		countryCodes: [],
		isFund: false,
		kind: "special",
	}),
	Object.freeze({
		alphabeticCode: "XXX",
		numericCode: "999",
		minorUnits: null,
		name: "The codes assigned for transactions where no currency is involved",
		countryCodes: [],
		isFund: false,
		kind: "special",
	}),
	Object.freeze({
		alphabeticCode: "YER",
		numericCode: "886",
		minorUnits: 2,
		name: "Yemeni Rial",
		countryCodes: ["YE"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "ZAR",
		numericCode: "710",
		minorUnits: 2,
		name: "Rand",
		countryCodes: ["LS", "NA", "ZA"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "ZMW",
		numericCode: "967",
		minorUnits: 2,
		name: "Zambian Kwacha",
		countryCodes: ["ZM"],
		isFund: false,
		kind: "fiat",
	}),
	Object.freeze({
		alphabeticCode: "ZWG",
		numericCode: "924",
		minorUnits: 2,
		name: "Zimbabwe Gold",
		countryCodes: ["ZW"],
		isFund: false,
		kind: "fiat",
	}),
]);
