// AUTO-GENERATED — do not edit by hand.
// Regenerate with `npm run generate` after refreshing data via `npm run fetch-data`.
// Source: list-three.xml (SIX Group)

import type { HistoricCurrency } from "./types.js";

/**
 * ISO 4217 publication date of the historic data embedded in this module.
 */
export const HISTORIC_PUBLISHED_AT = "2026-01-01" as const;

/**
 * Frozen array of every withdrawn ISO 4217 currency, sorted by alphabetic
 * code then by withdrawal date. Historic codes may collide with current codes,
 * so callers should treat this list as informational only.
 */
export const HISTORIC_CURRENCIES: readonly HistoricCurrency[] = Object.freeze([
	Object.freeze({
		alphabeticCode: "ADP",
		numericCode: "020",
		name: "Andorran Peseta",
		withdrawalDate: "2003-07",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "AFA",
		numericCode: "004",
		name: "Afghani",
		withdrawalDate: "2003-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ALK",
		numericCode: "008",
		name: "Old Lek",
		withdrawalDate: "1989-12",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ANG",
		numericCode: "532",
		name: "Netherlands Antillean Guilder",
		withdrawalDate: "2010-10",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ANG",
		numericCode: "532",
		name: "Netherlands Antillean Guilder",
		withdrawalDate: "2025-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "AOK",
		numericCode: "024",
		name: "Kwanza",
		withdrawalDate: "1991-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "AON",
		numericCode: "024",
		name: "New Kwanza",
		withdrawalDate: "2000-02",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "AOR",
		numericCode: "982",
		name: "Kwanza Reajustado",
		withdrawalDate: "2000-02",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ARA",
		numericCode: "032",
		name: "Austral",
		withdrawalDate: "1992-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ARP",
		numericCode: "032",
		name: "Peso Argentino",
		withdrawalDate: "1985-07",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ARY",
		numericCode: "032",
		name: "Peso",
		withdrawalDate: "1989 to 1990",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ATS",
		numericCode: "040",
		name: "Schilling",
		withdrawalDate: "2002-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "AYM",
		numericCode: "945",
		name: "Azerbaijan Manat",
		withdrawalDate: "2005-10",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "AZM",
		numericCode: "031",
		name: "Azerbaijanian Manat",
		withdrawalDate: "2005-12",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "BAD",
		numericCode: "070",
		name: "Dinar",
		withdrawalDate: "1998-07",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "BEC",
		numericCode: "993",
		name: "Convertible Franc",
		withdrawalDate: "1990-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "BEF",
		numericCode: "056",
		name: "Belgian Franc",
		withdrawalDate: "2002-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "BEL",
		numericCode: "992",
		name: "Financial Franc",
		withdrawalDate: "1990-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "BGJ",
		numericCode: "100",
		name: "Lev A/52",
		withdrawalDate: "1989 to 1990",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "BGK",
		numericCode: "100",
		name: "Lev A/62",
		withdrawalDate: "1989 to 1990",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "BGL",
		numericCode: "100",
		name: "Lev",
		withdrawalDate: "2003-11",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "BGN",
		numericCode: "975",
		name: "Bulgarian Lev",
		withdrawalDate: "2026-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "BOP",
		numericCode: "068",
		name: "Peso boliviano",
		withdrawalDate: "1987-02",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "BRB",
		numericCode: "076",
		name: "Cruzeiro",
		withdrawalDate: "1986-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "BRC",
		numericCode: "076",
		name: "Cruzado",
		withdrawalDate: "1989-02",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "BRE",
		numericCode: "076",
		name: "Cruzeiro",
		withdrawalDate: "1993-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "BRN",
		numericCode: "076",
		name: "New Cruzado",
		withdrawalDate: "1990-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "BRR",
		numericCode: "987",
		name: "Cruzeiro Real",
		withdrawalDate: "1994-07",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "BUK",
		numericCode: "104",
		name: "Kyat",
		withdrawalDate: "1990-02",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "BYB",
		numericCode: "112",
		name: "Belarusian Ruble",
		withdrawalDate: "2001-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "BYR",
		numericCode: "974",
		name: "Belarusian Ruble",
		withdrawalDate: "2017-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "CHC",
		numericCode: "948",
		name: "WIR Franc (for electronic)",
		withdrawalDate: "2004-11",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "CSD",
		numericCode: "891",
		name: "Serbian Dinar",
		withdrawalDate: "2006-10",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "CSJ",
		numericCode: "203",
		name: "Krona A/53",
		withdrawalDate: "1989 to 1990",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "CSK",
		numericCode: "200",
		name: "Koruna",
		withdrawalDate: "1993-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "CUC",
		numericCode: "931",
		name: "Peso Convertible",
		withdrawalDate: "2021-06",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "CYP",
		numericCode: "196",
		name: "Cyprus Pound",
		withdrawalDate: "2008-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "DDM",
		numericCode: "278",
		name: "Mark der DDR",
		withdrawalDate: "1990-07 to 1990-09",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "DEM",
		numericCode: "276",
		name: "Deutsche Mark",
		withdrawalDate: "2002-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ECS",
		numericCode: "218",
		name: "Sucre",
		withdrawalDate: "2000-09",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ECV",
		numericCode: "983",
		name: "Unidad de Valor Constante (UVC)",
		withdrawalDate: "2000-09",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "EEK",
		numericCode: "233",
		name: "Kroon",
		withdrawalDate: "2011-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ESA",
		numericCode: "996",
		name: "Spanish Peseta",
		withdrawalDate: "1978 to 1981",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ESB",
		numericCode: "995",
		name: '"A" Account (convertible Peseta Account)',
		withdrawalDate: "1994-12",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ESP",
		numericCode: "724",
		name: "Spanish Peseta",
		withdrawalDate: "2002-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "EUR",
		numericCode: "978",
		name: "Euro",
		withdrawalDate: "2006-10",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "FIM",
		numericCode: "246",
		name: "Markka",
		withdrawalDate: "2002-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "FRF",
		numericCode: "250",
		name: "French Franc",
		withdrawalDate: "1999-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "FRF",
		numericCode: "250",
		name: "French Franc",
		withdrawalDate: "2002-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "GEK",
		numericCode: "268",
		name: "Georgian Coupon",
		withdrawalDate: "1995-10",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "GHC",
		numericCode: "288",
		name: "Cedi",
		withdrawalDate: "2008-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "GHP",
		numericCode: "939",
		name: "Ghana Cedi",
		withdrawalDate: "2007-06",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "GNE",
		numericCode: "324",
		name: "Syli",
		withdrawalDate: "1989-12",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "GNS",
		numericCode: "324",
		name: "Syli",
		withdrawalDate: "1986-02",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "GQE",
		numericCode: "226",
		name: "Ekwele",
		withdrawalDate: "1986-06",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "GRD",
		numericCode: "300",
		name: "Drachma",
		withdrawalDate: "2002-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "GWE",
		numericCode: "624",
		name: "Guinea Escudo",
		withdrawalDate: "1978 to 1981",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "GWP",
		numericCode: "624",
		name: "Guinea-Bissau Peso",
		withdrawalDate: "1997-05",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "HRD",
		numericCode: "191",
		name: "Croatian Dinar",
		withdrawalDate: "1995-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "HRK",
		numericCode: "191",
		name: "Croatian Kuna",
		withdrawalDate: "2015-06",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "HRK",
		numericCode: "191",
		name: "Kuna",
		withdrawalDate: "2023-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "IDR",
		numericCode: "360",
		name: "Rupiah",
		withdrawalDate: "2002-07",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "IEP",
		numericCode: "372",
		name: "Irish Pound",
		withdrawalDate: "2002-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ILP",
		numericCode: "376",
		name: "Pound",
		withdrawalDate: "1978 to 1981",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ILR",
		numericCode: "376",
		name: "Old Shekel",
		withdrawalDate: "1989 to 1990",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ISJ",
		numericCode: "352",
		name: "Old Krona",
		withdrawalDate: "1989 to 1990",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ITL",
		numericCode: "380",
		name: "Italian Lira",
		withdrawalDate: "2002-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "LAJ",
		numericCode: "418",
		name: "Pathet Lao Kip",
		withdrawalDate: "1979-12",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "LSM",
		numericCode: "426",
		name: "Loti",
		withdrawalDate: "1985-05",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "LTL",
		numericCode: "440",
		name: "Lithuanian Litas",
		withdrawalDate: "2014-12",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "LTT",
		numericCode: "440",
		name: "Talonas",
		withdrawalDate: "1993-07",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "LUC",
		numericCode: "989",
		name: "Luxembourg Convertible Franc",
		withdrawalDate: "1990-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "LUF",
		numericCode: "442",
		name: "Luxembourg Franc",
		withdrawalDate: "2002-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "LUL",
		numericCode: "988",
		name: "Luxembourg Financial Franc",
		withdrawalDate: "1990-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "LVL",
		numericCode: "428",
		name: "Latvian Lats",
		withdrawalDate: "2014-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "LVR",
		numericCode: "428",
		name: "Latvian Ruble",
		withdrawalDate: "1994-12",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "MGF",
		numericCode: "450",
		name: "Malagasy Franc",
		withdrawalDate: "2004-12",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "MLF",
		numericCode: "466",
		name: "Mali Franc",
		withdrawalDate: "1984-11",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "MRO",
		numericCode: "478",
		name: "Ouguiya",
		withdrawalDate: "2017-12",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "MTL",
		numericCode: "470",
		name: "Maltese Lira",
		withdrawalDate: "2008-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "MTP",
		numericCode: "470",
		name: "Maltese Pound",
		withdrawalDate: "1983-06",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "MVQ",
		numericCode: "462",
		name: "Maldive Rupee",
		withdrawalDate: "1989-12",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "MWK",
		numericCode: "454",
		name: "Kwacha",
		withdrawalDate: "2016-02",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "MXP",
		numericCode: "484",
		name: "Mexican Peso",
		withdrawalDate: "1993-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "MZE",
		numericCode: "508",
		name: "Mozambique Escudo",
		withdrawalDate: "1978 to 1981",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "MZM",
		numericCode: "508",
		name: "Mozambique Metical",
		withdrawalDate: "2006-06",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "NIC",
		numericCode: "558",
		name: "Cordoba",
		withdrawalDate: "1990-10",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "NLG",
		numericCode: "528",
		name: "Netherlands Guilder",
		withdrawalDate: "2002-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "PEH",
		numericCode: "604",
		name: "Sol",
		withdrawalDate: "1989 to 1990",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "PEI",
		numericCode: "604",
		name: "Inti",
		withdrawalDate: "1991-07",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "PEN",
		numericCode: "604",
		name: "Nuevo Sol",
		withdrawalDate: "2015-12",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "PES",
		numericCode: "604",
		name: "Sol",
		withdrawalDate: "1986-02",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "PLZ",
		numericCode: "616",
		name: "Zloty",
		withdrawalDate: "1997-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "PTE",
		numericCode: "620",
		name: "Portuguese Escudo",
		withdrawalDate: "2002-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "RHD",
		numericCode: "716",
		name: "Rhodesian Dollar",
		withdrawalDate: "1978 to 1981",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ROK",
		numericCode: "642",
		name: "Leu A/52",
		withdrawalDate: "1989 to 1990",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ROL",
		numericCode: "642",
		name: "Old Leu",
		withdrawalDate: "2005-06",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "RON",
		numericCode: "946",
		name: "New Romanian Leu",
		withdrawalDate: "2015-06",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "RUR",
		numericCode: "810",
		name: "Russian Ruble",
		withdrawalDate: "1993-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "RUR",
		numericCode: "810",
		name: "Russian Ruble",
		withdrawalDate: "1993-10",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "RUR",
		numericCode: "810",
		name: "Russian Ruble",
		withdrawalDate: "1993-12",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "RUR",
		numericCode: "810",
		name: "Russian Ruble",
		withdrawalDate: "1994-04",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "RUR",
		numericCode: "810",
		name: "Russian Ruble",
		withdrawalDate: "1994-05",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "RUR",
		numericCode: "810",
		name: "Russian Ruble",
		withdrawalDate: "1994-06",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "RUR",
		numericCode: "810",
		name: "Russian Ruble",
		withdrawalDate: "1994-07",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "RUR",
		numericCode: "810",
		name: "Russian Ruble",
		withdrawalDate: "1994-08",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "RUR",
		numericCode: "810",
		name: "Russian Ruble",
		withdrawalDate: "1995-05",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "RUR",
		numericCode: "810",
		name: "Russian Ruble",
		withdrawalDate: "2004-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "SDD",
		numericCode: "736",
		name: "Sudanese Dinar",
		withdrawalDate: "2007-07",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "SDG",
		numericCode: "938",
		name: "Sudanese Pound",
		withdrawalDate: "2012-09",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "SDP",
		numericCode: "736",
		name: "Sudanese Pound",
		withdrawalDate: "1998-06",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "SIT",
		numericCode: "705",
		name: "Tolar",
		withdrawalDate: "2007-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "SKK",
		numericCode: "703",
		name: "Slovak Koruna",
		withdrawalDate: "2009-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "SLL",
		numericCode: "694",
		name: "Leone",
		withdrawalDate: "2023-12",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "SRG",
		numericCode: "740",
		name: "Surinam Guilder",
		withdrawalDate: "2003-12",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "STD",
		numericCode: "678",
		name: "Dobra",
		withdrawalDate: "2017-12",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "SUR",
		numericCode: "810",
		name: "Rouble",
		withdrawalDate: "1990-12",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "SZL",
		numericCode: "748",
		name: "Lilangeni",
		withdrawalDate: "2018-08",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "TJR",
		numericCode: "762",
		name: "Tajik Ruble",
		withdrawalDate: "2001-04",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "TMM",
		numericCode: "795",
		name: "Turkmenistan Manat",
		withdrawalDate: "2009-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "TPE",
		numericCode: "626",
		name: "Timor Escudo",
		withdrawalDate: "2002-11",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "TRL",
		numericCode: "792",
		name: "Old Turkish Lira",
		withdrawalDate: "2005-12",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "TRY",
		numericCode: "949",
		name: "New Turkish Lira",
		withdrawalDate: "2009-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "UAK",
		numericCode: "804",
		name: "Karbovanet",
		withdrawalDate: "1996-09",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "UGS",
		numericCode: "800",
		name: "Uganda Shilling",
		withdrawalDate: "1987-05",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "UGW",
		numericCode: "800",
		name: "Old Shilling",
		withdrawalDate: "1989 to 1990",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "USS",
		numericCode: "998",
		name: "US Dollar (Same day)",
		withdrawalDate: "2014-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "UYN",
		numericCode: "858",
		name: "Old Uruguay Peso",
		withdrawalDate: "1989-12",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "UYP",
		numericCode: "858",
		name: "Uruguayan Peso",
		withdrawalDate: "1993-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "VEB",
		numericCode: "862",
		name: "Bolivar",
		withdrawalDate: "2008-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "VEF",
		numericCode: "937",
		name: "Bolivar Fuerte",
		withdrawalDate: "2011-12",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "VEF",
		numericCode: "937",
		name: "Bolivar",
		withdrawalDate: "2016-02",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "VEF",
		numericCode: "937",
		name: "Bolívar",
		withdrawalDate: "2018-08",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "VNC",
		numericCode: "704",
		name: "Old Dong",
		withdrawalDate: "1989-1990",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "XEU",
		numericCode: "954",
		name: "European Currency Unit (E.C.U)",
		withdrawalDate: "1999-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "XFO",
		numericCode: null,
		name: "Gold-Franc",
		withdrawalDate: "2006-10",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "XFU",
		numericCode: null,
		name: "UIC-Franc",
		withdrawalDate: "2013-11",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "XRE",
		numericCode: null,
		name: "RINET Funds Code",
		withdrawalDate: "1999-11",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "YDD",
		numericCode: "720",
		name: "Yemeni Dinar",
		withdrawalDate: "1991-09",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "YUD",
		numericCode: "890",
		name: "New Yugoslavian Dinar",
		withdrawalDate: "1990-01",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "YUM",
		numericCode: "891",
		name: "New Dinar",
		withdrawalDate: "2003-07",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "YUN",
		numericCode: "890",
		name: "Yugoslavian Dinar",
		withdrawalDate: "1995-11",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ZAL",
		numericCode: "991",
		name: "Financial Rand",
		withdrawalDate: "1995-03",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ZMK",
		numericCode: "894",
		name: "Zambian Kwacha",
		withdrawalDate: "2012-12",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ZRN",
		numericCode: "180",
		name: "New Zaire",
		withdrawalDate: "1999-06",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ZRZ",
		numericCode: "180",
		name: "Zaire",
		withdrawalDate: "1994-02",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ZWC",
		numericCode: "716",
		name: "Rhodesian Dollar",
		withdrawalDate: "1989-12",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ZWD",
		numericCode: "716",
		name: "Zimbabwe Dollar (old)",
		withdrawalDate: "2006-08",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ZWD",
		numericCode: "716",
		name: "Zimbabwe Dollar",
		withdrawalDate: "2008-08",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ZWL",
		numericCode: "932",
		name: "Zimbabwe Dollar",
		withdrawalDate: "2024-09",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ZWN",
		numericCode: "942",
		name: "Zimbabwe Dollar (new)",
		withdrawalDate: "2006-09",
	} satisfies HistoricCurrency),
	Object.freeze({
		alphabeticCode: "ZWR",
		numericCode: "935",
		name: "Zimbabwe Dollar",
		withdrawalDate: "2009-06",
	} satisfies HistoricCurrency),
]);
