import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseTSV } from "../src/parser";
import type {
	ParsedNACEBEL,
	ParsedNACEHeading,
	ParsedNACEStructure,
} from "../src/types";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const rootDir = join(scriptDir, "..");
const dataDir = join(rootDir, "data");
const generatedDir = join(rootDir, "src", "generated");

mkdirSync(generatedDir, { recursive: true });

const HEADER = `// Auto-generated file. Do not edit manually.
// Generated by scripts/generateDataModules.ts
`;

function readData(relativePath: string): string {
	return readFileSync(join(dataDir, relativePath), "utf-8");
}

function serialize(value: unknown): string {
	return JSON.stringify(value, null, "\t");
}

/** Core NACE (EU) headings and structure — shared by every country module. */
function generateNACEDataModule(): void {
	console.log("Generating NACE data module...");

	const headings = parseTSV<ParsedNACEHeading>(
		readData("nace/NACE_Rev2.1_Heading_All_Languages.tsv"),
	);
	const structure = parseTSV<ParsedNACEStructure>(
		readData("nace/NACE_Rev2.1_Structure_Explanatory_Notes_EN.tsv"),
	);

	const module = `${HEADER}
import type { ParsedNACEHeading, ParsedNACEStructure } from "../types";

export const naceHeadings: ParsedNACEHeading[] = ${serialize(headings)};

export const naceStructure: ParsedNACEStructure[] = ${serialize(structure)};
`;

	writeFileSync(join(generatedDir, "naceData.ts"), module);
	console.log("✓ Generated naceData.ts");
}

/** Belgian NACEBEL delta only — the shared NACE core lives in naceData.ts. */
function generateNACEBELDataModule(): void {
	console.log("Generating NACEBEL data module...");

	const nacebel = parseTSV<ParsedNACEBEL>(readData("nacebel/codes-NACEBEL-2025.tsv"));

	const module = `${HEADER}
import type { ParsedNACEBEL } from "../types";

export const nacebelData: ParsedNACEBEL[] = ${serialize(nacebel)};
`;

	writeFileSync(join(generatedDir, "nacebelData.ts"), module);
	console.log("✓ Generated nacebelData.ts");
}

/**
 * NACEBEL explanatory notes ("Explication" / "Toelichting") as Markdown, per
 * language, with cross-references rendered as `[[code]]` wikilinks. Keyed by
 * normalized code. Built from the EU NACE Rev. 2.1 notes (levels 1-4, the source
 * KBO serves) plus sole-child subclass propagation, then translated to FR/NL/DE.
 */
function generateNACEBELDescriptionsModule(): void {
	console.log("Generating NACEBEL descriptions module...");

	const raw = readData("nacebel/nacebel-descriptions-2025.json");
	const descriptions = JSON.parse(raw) as Record<
		string,
		{ en: string; fr?: string; nl?: string; de?: string }
	>;

	const module = `${HEADER}
import type { LanguageDescriptions } from "../types";

export const nacebelDescriptions: Record<string, LanguageDescriptions> = ${serialize(descriptions)};
`;

	writeFileSync(join(generatedDir, "nacebelDescriptions.ts"), module);
	console.log(
		`✓ Generated nacebelDescriptions.ts (${Object.keys(descriptions).length} notes)`,
	);
}

console.log("Starting data module generation...\n");
generateNACEDataModule();
generateNACEBELDataModule();
generateNACEBELDescriptionsModule();
console.log("\n✓ Data modules generated in", generatedDir);
