import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { type FormatConfig, format } from "oxfmt";
import {
	NACEBEL_NOTE_LANGUAGES,
	OPTIONAL_LANGUAGES,
	type OptionalLanguage,
} from "../src/languageList";
import { parseTSV } from "../src/parser";
import type {
	ParsedNACEBEL,
	ParsedNACEHeading,
	ParsedNACEStructure,
} from "../src/types";
import { normalizeCode } from "../src/utils";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const rootDir = join(scriptDir, "..");
const dataDir = join(rootDir, "data");
const generatedDir = join(rootDir, "src", "generated");
const langDir = join(generatedDir, "lang");
const nacebelLangDir = join(generatedDir, "nacebel", "lang");

// Regenerate from scratch: a language dropped upstream must not leave a stale
// module behind that the build config would still try to pick up.
rmSync(langDir, { recursive: true, force: true });
rmSync(join(generatedDir, "nacebel"), { recursive: true, force: true });
mkdirSync(generatedDir, { recursive: true });
mkdirSync(langDir, { recursive: true });
mkdirSync(nacebelLangDir, { recursive: true });

const HEADER = `// Auto-generated file. Do not edit manually.
// Generated by scripts/generateDataModules.ts
`;

function readData(relativePath: string): string {
	return readFileSync(join(dataDir, relativePath), "utf-8");
}

/**
 * oxfmt's programmatic API does not discover `.oxfmtrc.json` the way its CLI
 * does, so find the repo config and pass it through. Reading the real file
 * rather than hardcoding options is what keeps generated output byte-identical
 * to whatever `oxfmt --check` expects.
 */
function loadFormatConfig(): FormatConfig {
	let directory = scriptDir;

	for (;;) {
		const candidate = join(directory, ".oxfmtrc.json");
		if (existsSync(candidate)) {
			return JSON.parse(readFileSync(candidate, "utf-8")) as FormatConfig;
		}

		const parent = dirname(directory);
		if (parent === directory) {
			throw new Error(`no .oxfmtrc.json found above ${scriptDir}`);
		}
		directory = parent;
	}
}

const formatConfig = loadFormatConfig();

/** Writes a generated module already formatted, so no later pass has to fix it. */
async function writeModule(path: string, source: string): Promise<void> {
	const { code, errors } = await format(path, source, formatConfig);

	if (errors.length > 0) {
		const detail = errors.map((error) => error.message).join("\n");
		throw new Error(`oxfmt could not format ${path}:\n${detail}`);
	}

	writeFileSync(path, code);
}

function serialize(value: unknown): string {
	return JSON.stringify(value, null, "\t");
}

function languageColumn(language: OptionalLanguage): string {
	return `${language.toUpperCase()}_DESC`;
}

/** One opt-in translation module per language, imported as `nace-codes/lang/<code>`. */
async function generateLanguageModule(
	directory: string,
	language: OptionalLanguage,
	field: "descriptions" | "explanatoryNotes",
	entries: Record<string, string>,
	depth: number,
): Promise<void> {
	const typesPath = `${"../".repeat(depth)}types`;
	const module = `${HEADER}
import type { LanguagePack } from "${typesPath}";

const pack: LanguagePack = {
	language: "${language}",
	${field}: ${serialize(entries)},
};

export default pack;
`;

	await writeModule(join(directory, `${language}.ts`), module);
}

/**
 * Core NACE (EU) headings and structure — shared by every country module. Only
 * English descriptions land here; the other 23 languages become separate
 * `lang/<code>.ts` modules so they stay out of the default bundle.
 */
async function generateNACEDataModule(): Promise<void> {
	console.log("Generating NACE data module...");

	const headings = parseTSV<ParsedNACEHeading>(
		readData("nace/NACE_Rev2.1_Heading_All_Languages.tsv"),
	);
	const structure = parseTSV<ParsedNACEStructure>(
		readData("nace/NACE_Rev2.1_Structure_Explanatory_Notes_EN.tsv"),
	);

	const englishHeadings = headings.map((heading) => ({
		NACE_CODE: heading.NACE_CODE,
		EN_DESC: heading.EN_DESC,
	}));

	const module = `${HEADER}
import type { ParsedNACEHeading, ParsedNACEStructure } from "../types";

export const naceHeadings: ParsedNACEHeading[] = ${serialize(englishHeadings)};

export const naceStructure: ParsedNACEStructure[] = ${serialize(structure)};
`;

	await writeModule(join(generatedDir, "naceData.ts"), module);
	console.log("✓ Generated naceData.ts (en only)");

	// One module per language, each to its own file, so they can all be written
	// at once.
	await Promise.all(
		OPTIONAL_LANGUAGES.map(async (language) => {
			const column = languageColumn(language);
			const descriptions: Record<string, string> = {};

			for (const heading of headings) {
				const value = (
					heading as unknown as Record<string, string | undefined>
				)[column];
				if (value !== undefined && value !== "") {
					descriptions[normalizeCode(heading.NACE_CODE)] = value;
				}
			}

			await generateLanguageModule(
				langDir,
				language,
				"descriptions",
				descriptions,
				2,
			);
			console.log(
				`✓ Generated lang/${language}.ts (${Object.keys(descriptions).length})`,
			);
		}),
	);
}

/** Belgian NACEBEL delta only — the shared NACE core lives in naceData.ts. */
async function generateNACEBELDataModule(): Promise<void> {
	console.log("Generating NACEBEL data module...");

	const nacebel = parseTSV<ParsedNACEBEL>(readData("nacebel/codes-NACEBEL-2025.tsv"));

	const module = `${HEADER}
import type { ParsedNACEBEL } from "../types";

export const nacebelData: ParsedNACEBEL[] = ${serialize(nacebel)};
`;

	await writeModule(join(generatedDir, "nacebelData.ts"), module);
	console.log("✓ Generated nacebelData.ts");
}

/**
 * NACEBEL explanatory notes ("Explication" / "Toelichting") as Markdown, per
 * language, with cross-references rendered as `[[code]]` wikilinks. Keyed by
 * normalized code. Built from the EU NACE Rev. 2.1 notes (levels 1-4, the source
 * KBO serves) plus sole-child subclass propagation, then translated to FR/NL/DE.
 */
async function generateNACEBELDescriptionsModule(): Promise<void> {
	console.log("Generating NACEBEL descriptions module...");

	const raw = readData("nacebel/nacebel-descriptions-2025.json");
	const descriptions = JSON.parse(raw) as Record<
		string,
		{ en: string; fr?: string; nl?: string; de?: string }
	>;

	const english: Record<string, { en: string }> = {};
	for (const [code, note] of Object.entries(descriptions)) {
		english[code] = { en: note.en };
	}

	const module = `${HEADER}
import type { LanguageDescriptions } from "../types";

export const nacebelDescriptions: Record<string, LanguageDescriptions> = ${serialize(english)};
`;

	await writeModule(join(generatedDir, "nacebelDescriptions.ts"), module);
	console.log(
		`✓ Generated nacebelDescriptions.ts (${Object.keys(english).length} notes, en only)`,
	);

	// Same here: one file per language, so write them concurrently.
	await Promise.all(
		NACEBEL_NOTE_LANGUAGES.map(async (language) => {
			const notes: Record<string, string> = {};

			for (const [code, note] of Object.entries(descriptions)) {
				const translated = note[language];
				if (translated !== undefined && translated !== "") {
					notes[code] = translated;
				}
			}

			await generateLanguageModule(
				nacebelLangDir,
				language,
				"explanatoryNotes",
				notes,
				3,
			);
			console.log(
				`✓ Generated nacebel/lang/${language}.ts (${Object.keys(notes).length} notes)`,
			);
		}),
	);
}

console.log("Starting data module generation...\n");
await generateNACEDataModule();
await generateNACEBELDataModule();
await generateNACEBELDescriptionsModule();
console.log("\n✓ Data modules generated in", generatedDir);
