import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseTSV } from "../src/parser";
import type {
	ParsedNACEBEL,
	ParsedNACEHeading,
	ParsedNACEStructure,
} from "../src/types";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const rootDir = join(scriptDir, "..");
const dataDir = join(rootDir, "data");
const generatedDir = join(rootDir, "src", "generated");

mkdirSync(generatedDir, { recursive: true });

const HEADER = `// Auto-generated file. Do not edit manually.
// Generated by scripts/generateDataModules.ts
`;

function readData(relativePath: string): string {
	return readFileSync(join(dataDir, relativePath), "utf-8");
}

function serialize(value: unknown): string {
	return JSON.stringify(value, null, "\t");
}

/** Core NACE (EU) headings and structure — shared by every country module. */
function generateNACEDataModule(): void {
	console.log("Generating NACE data module...");

	const headings = parseTSV<ParsedNACEHeading>(
		readData("nace/NACE_Rev2.1_Heading_All_Languages.tsv"),
	);
	const structure = parseTSV<ParsedNACEStructure>(
		readData("nace/NACE_Rev2.1_Structure_Explanatory_Notes_EN.tsv"),
	);

	const module = `${HEADER}
import type { ParsedNACEHeading, ParsedNACEStructure } from "../types";

export const naceHeadings: ParsedNACEHeading[] = ${serialize(headings)};

export const naceStructure: ParsedNACEStructure[] = ${serialize(structure)};
`;

	writeFileSync(join(generatedDir, "naceData.ts"), module);
	console.log("✓ Generated naceData.ts");
}

/** Belgian NACEBEL delta only — the shared NACE core lives in naceData.ts. */
function generateNACEBELDataModule(): void {
	console.log("Generating NACEBEL data module...");

	const nacebel = parseTSV<ParsedNACEBEL>(readData("nacebel/codes-NACEBEL-2025.tsv"));

	const module = `${HEADER}
import type { ParsedNACEBEL } from "../types";

export const nacebelData: ParsedNACEBEL[] = ${serialize(nacebel)};
`;

	writeFileSync(join(generatedDir, "nacebelData.ts"), module);
	console.log("✓ Generated nacebelData.ts");
}

console.log("Starting data module generation...\n");
generateNACEDataModule();
generateNACEBELDataModule();
console.log("\n✓ Data modules generated in", generatedDir);
